import type { Sector, TechnologyId } from '@/lib/types';

export type HazardCategory =
  | 'access'
  | 'height'
  | 'electrical'
  | 'manual_handling'
  | 'plant'
  | 'lifting'
  | 'fire'
  | 'weather'
  | 'public'
  | 'substances'
  | 'structural'
  | 'confined'
  | 'lone_working'
  | 'health';

export const HAZARD_CATEGORIES: { id: HazardCategory; label: string }[] = [
  { id: 'access', label: 'Access & egress' },
  { id: 'height', label: 'Working at height' },
  { id: 'electrical', label: 'Electrical' },
  { id: 'manual_handling', label: 'Manual handling' },
  { id: 'plant', label: 'Plant & equipment' },
  { id: 'lifting', label: 'Lifting operations' },
  { id: 'fire', label: 'Fire & thermal' },
  { id: 'weather', label: 'Weather & environment' },
  { id: 'public', label: 'Public & occupants' },
  { id: 'substances', label: 'Hazardous substances' },
  { id: 'structural', label: 'Structural' },
  { id: 'confined', label: 'Confined & restricted spaces' },
  { id: 'lone_working', label: 'Lone & remote working' },
  { id: 'health', label: 'Occupational health' },
];

export type HazardTemplate = {
  id: string;
  category: HazardCategory;
  hazard: string;
  /** 'all' means the hazard is offered for every technology. */
  technologies: TechnologyId[] | 'all';
  /** 'all' means it applies to both residential and commercial work. */
  sectors: Sector[] | 'all';
  whoIsAtRisk: string[];
  initialLikelihood: number;
  initialSeverity: number;
  controls: string[];
  residualLikelihood: number;
  residualSeverity: number;
  /** Included automatically when the technology is selected. */
  core?: boolean;
};

const OPERATIVES = 'Operatives';
const PUBLIC = 'Members of the public';
const OCCUPANTS = 'Building occupants';
const CLIENT = 'Client / site staff';
const OTHER_TRADES = 'Other trades';

export const HAZARD_LIBRARY: HazardTemplate[] = [
  // ==========================================================================
  // Access & egress
  // ==========================================================================
  {
    id: 'acc-site-access',
    category: 'access',
    hazard: 'Vehicle movements and reversing during site access, unloading and parking',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC, OTHER_TRADES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Site access route and parking agreed with the client before arrival and recorded in the project record.',
      'Vehicles reversed only with a banksman, or driven forward into position where the layout allows.',
      'Hazard lights and beacons used while unloading; high-visibility clothing worn at all times on the approach.',
      'Unloading zone coned off and kept clear of pedestrians for the duration of the offload.',
      'On commercial sites, the client traffic-management plan and one-way system are followed without exception.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'acc-slips-trips',
    category: 'access',
    hazard: 'Slips, trips and falls on the level from cables, tools, packaging and site debris',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, PUBLIC],
    initialLikelihood: 4,
    initialSeverity: 2,
    controls: [
      'Good housekeeping maintained throughout; work area cleared at each break and at the end of every shift.',
      'Trailing leads routed to the perimeter, covered with matting or run overhead where they cross a walkway.',
      'Packaging and waste removed to a designated skip or van as it is generated, not stockpiled.',
      'Safety footwear with slip-resistant soles worn at all times.',
      'Wet or icy surfaces gritted or cordoned; spills cleaned immediately.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'acc-restricted-egress',
    category: 'access',
    hazard: 'Obstruction of fire exits, escape routes or emergency equipment by materials and plant',
    technologies: 'all',
    sectors: ['commercial'],
    whoIsAtRisk: [OCCUPANTS, OPERATIVES, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Fire exits, escape routes, call points, extinguishers and riser cupboards identified at induction and kept clear.',
      'Materials stored only in the designated compound or laydown area agreed with the client.',
      'Any temporary obstruction agreed in writing with the responsible person and an alternative route signed.',
      'Access equipment struck and removed from escape corridors at the end of each shift.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
  },
  {
    id: 'acc-uneven-ground',
    category: 'access',
    hazard: 'Uneven, soft or sloping ground affecting access, plant stability and footing',
    technologies: ['solar_pv', 'small_wind', 'ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Ground conditions assessed at survey and re-checked on the day; work postponed if the ground is unfit for the plant.',
      'Trackway, ground-protection mats or spreader plates used under wheeled and outrigger plant.',
      'Excavations, service trenches and ditches identified, barriered and covered.',
      'Routes for carrying materials agreed and kept as short and level as practicable.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
  },

  // ==========================================================================
  // Working at height
  // ==========================================================================
  {
    id: 'wah-roof-fall',
    category: 'height',
    hazard: 'Fall from height from a pitched roof, roof edge or working platform',
    technologies: ['solar_pv', 'led_lighting', 'ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 5,
    controls: [
      'Work at height avoided where the task can be done from the ground; otherwise collective protection is used before personal protection.',
      'Independent scaffold with a double guardrail, toe board and edge protection erected by a competent scaffolder to TG20; handover certificate ("Scafftag") in place and checked before first use.',
      'Scaffold inspected before first use, every 7 days thereafter and after any event likely to have affected its stability; inspection record kept on site.',
      'Where a scaffold is not reasonably practicable, a MEWP or a man-safe system with a twin-lanyard harness on a rated anchor is used, and a rescue plan is in place before anyone is suspended.',
      'No work at height in wind above 23 mph (Beaufort 5), during heavy rain, ice, snow or lightning, or in the dark without adequate task lighting.',
      'Exclusion zone at ground level beneath all overhead work, barriered and signed.',
      'Operatives hold a current working-at-height / roof-work competence and have been briefed on this document.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'wah-fragile-surface',
    category: 'height',
    hazard: 'Fall through a fragile roof surface, rooflight, asbestos cement sheet or corroded decking',
    technologies: ['solar_pv', 'led_lighting'],
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'All roofs are treated as fragile until a competent survey proves otherwise; the survey is reviewed before mobilisation.',
      'Rooflights, translucent panels and fragile areas covered with load-bearing covers or protected with fixed guardrails before any access.',
      'Access limited to purlin lines and load-bearing structure only, identified and marked on a roof plan issued with this RAMS.',
      'Crawling boards or staging used where load spread is required; no walking on sheeting between supports.',
      'Fragile-surface warning signage installed at every access point onto the roof.',
      'Safety nets or a soft-landing system installed beneath the work area where a fall risk through the deck remains.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },
  {
    id: 'wah-flat-roof-edge',
    category: 'height',
    hazard: 'Fall from an unprotected flat roof edge while setting out ballasted arrays or plant',
    technologies: ['solar_pv', 'ashp', 'battery_storage'],
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Permanent edge protection confirmed adequate, or free-standing counterbalanced guardrail installed to the full working perimeter before work starts.',
      'Where guardrail is not practicable, a demarcation barrier is set no less than 2 m from the edge and no work takes place beyond it without a fall-restraint system.',
      'Fall restraint (not fall arrest) is the default: lanyards adjusted so the operative physically cannot reach the edge.',
      'Anchor points and man-safe lines are certified within the last 12 months; certificates held on file.',
      'Materials stacked no closer than 2 m to the edge and secured against wind uplift.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },
  {
    id: 'wah-ladder-misuse',
    category: 'height',
    hazard: 'Fall from a ladder or stepladder used for access or short-duration work',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Ladders used for access and for light, short-duration work only (under 30 minutes) where a safer alternative is not reasonably practicable.',
      'Class 1 / EN 131 ladders only; pre-use visual check each day and a formal inspection record maintained.',
      'Ladders set at 75 degrees (1:4), tied at the stile or footed, and extended at least 1 m above the landing point.',
      'Three points of contact maintained; no over-reaching and no carrying of materials up a ladder — a hoist line or second operative is used.',
      'Podium steps or a tower used in preference to a stepladder for any task requiring both hands.',
    ],
    residualLikelihood: 2,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'wah-mewp',
    category: 'height',
    hazard: 'MEWP overturn, entrapment or ejection during elevated work',
    technologies: ['solar_pv', 'led_lighting', 'small_wind', 'ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Operators hold a current IPAF licence for the category in use; a trained ground rescue person is present whenever the platform is elevated.',
      'MEWP within its LOLER thorough examination date (6-monthly); certificate held on site.',
      'Ground bearing capacity checked, outriggers fully deployed on spreader plates, machine level before elevating.',
      'Restraint harness with a short lanyard clipped to the designated platform anchor in a boom-type MEWP.',
      'Overhead obstructions and services surveyed and an exclusion zone maintained; secondary guarding fitted where crush risk exists.',
      'Emergency lowering controls identified and demonstrated at the pre-start briefing.',
      'Machine isolated and keys removed when unattended.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'wah-tower-scaffold',
    category: 'height',
    hazard: 'Mobile tower scaffold collapse, overturn or fall during erection, use or movement',
    technologies: ['led_lighting', 'ashp', 'battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 4,
    controls: [
      'Towers erected, altered and dismantled only by PASMA-trained operatives using the 3T or AGR method.',
      'Erected to the manufacturer instruction; stabilisers or outriggers fitted, castors locked, tower plumb and level.',
      'Inspected before first use and every 7 days; tag system completed.',
      'Never moved with people, tools or materials on the platform; height reduced before repositioning.',
      'Maximum safe working load observed; access via the internal ladder only.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
  },
  {
    id: 'wah-dropped-objects',
    category: 'height',
    hazard: 'Objects, tools or components falling from height onto people below',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC, OCCUPANTS, OTHER_TRADES],
    initialLikelihood: 4,
    initialSeverity: 4,
    controls: [
      'Exclusion zone established below all overhead work using barriers, cones and signage; policed by the supervisor.',
      'Toe boards, brick guards or debris netting fitted to scaffolds and platforms.',
      'Tools tethered or carried in a closed tool belt; nothing left loose on a roof or platform.',
      'Materials never thrown or dropped — a hoist, gin wheel or chute is used and the drop zone is controlled.',
      'Hard hats worn by everyone within the exclusion zone and its approaches.',
      'Loose materials on roofs secured or removed before leaving site, particularly ahead of forecast wind.',
    ],
    residualLikelihood: 2,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'wah-rescue',
    category: 'height',
    hazard: 'Suspension trauma following an arrested fall with no means of prompt recovery',
    technologies: ['solar_pv', 'small_wind', 'led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'A written rescue plan is in place and briefed before any fall-arrest system is used; work does not start without it.',
      'Rescue must be achievable within 10 minutes of an arrest — no reliance on the emergency services as the primary means.',
      'Rescue kit (descent device or rescue pole) held on site, in date, and at least two operatives trained in its use.',
      'Never lone working where fall arrest is in use.',
      'Suspension trauma straps fitted to all harnesses; casualty kept in a seated, not flat, position after recovery until assessed.',
      'Ambulance access route and the nearest A&E identified and recorded on the cover sheet.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'wah-tower-climb',
    category: 'height',
    hazard: 'Fall while climbing a turbine tower or mast, or during nacelle access',
    technologies: ['small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Tower climbed only using the fitted fall-arrest rail or cable system with a compatible, in-date travelling arrester.',
      'Operatives hold current GWO Working at Height (or equivalent) including tower rescue, refreshed within 24 months.',
      'Minimum of two climbers; the ground person maintains constant radio contact and holds the rescue kit.',
      'Climb aborted if wind exceeds the manufacturer limit (typically 20 m/s at hub height), in lightning risk, or in icing conditions.',
      'Rotor locked and the turbine electrically isolated and proven dead before any tower ascent.',
      'Tower ladder, anchor points and arrest system inspected before use and formally examined every 6 months.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },

  // ==========================================================================
  // Electrical
  // ==========================================================================
  {
    id: 'elec-live-working',
    category: 'electrical',
    hazard: 'Electric shock or burn from contact with live AC conductors during connection works',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'All work is carried out dead. Live working is not permitted; testing that requires energisation is done with insulated tools and appropriate PPE only after a written justification.',
      'Safe isolation to the HSE GS38 procedure: identify, isolate, secure with a personal lock and unique key, prove the tester on a proving unit, test dead at every conductor, re-prove the tester.',
      'Lock-off device and a caution notice applied at the point of isolation; the key is retained by the operative doing the work.',
      'Only Part P / 18th Edition qualified electricians (BS 7671) carry out connection works; ECS or equivalent card held and in date.',
      'GS38-compliant test leads and probes with fused, shrouded tips; instruments calibrated within 12 months.',
      'Existing installation condition assessed before connection; defects reported and not worked around.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'elec-dc-live',
    category: 'electrical',
    hazard: 'DC shock and arc flash — PV strings are live in any daylight and cannot be switched off',
    technologies: ['solar_pv', 'battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 5,
    controls: [
      'All operatives briefed that modules generate voltage whenever illuminated — there is no "dead" state in daylight.',
      'Modules kept covered with opaque sheeting, or connectors left unmated, until the string is ready for termination.',
      'Strings built up one module at a time so open-circuit voltage never exceeds a safe handling level; string voltage measured before connection to the inverter and checked against the design.',
      'DC connectors (MC4 or equivalent) are of a single matched manufacturer, crimped with the correct tool and torque, and never mated or broken under load.',
      'DC isolator opened before breaking any connection; the inverter is shut down in the manufacturer sequence (AC first, then DC).',
      'Class 0 insulating gloves, arc-rated long sleeves and face protection worn where an arc-flash risk exists; no metal jewellery or watches.',
      'Insulated tools to IEC 60900 used for all DC work.',
      'Work stops in wet conditions — DC terminations are never made in rain.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'elec-battery-stored-energy',
    category: 'electrical',
    hazard: 'Stored energy in a battery bank — short circuit, arc flash and very high prospective fault current',
    technologies: ['battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Batteries remain in transit / shipping mode with breakers open until the system is fully assembled and pre-commissioning checks are complete.',
      'Insulated tools only; the battery compartment is treated as permanently live because it cannot be de-energised.',
      'All metal jewellery, watches and lanyards removed before opening any battery enclosure.',
      'Terminals covered with insulating caps at all times other than the moment of connection; one terminal exposed at a time.',
      'Correct polarity confirmed with a meter before every connection; torque settings applied to the manufacturer figure and marked.',
      'Class 0 gloves, arc-rated clothing and a face shield worn during connection and commissioning.',
      'Battery isolator and emergency stop located, labelled and demonstrated to the client at handover.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'elec-buried-services',
    category: 'electrical',
    hazard: 'Contact with buried or concealed services when drilling, chasing or excavating',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Existing service drawings obtained from the client and reviewed before any penetration; a permit to dig is raised on commercial sites.',
      'Cable avoidance tool and signal generator used to scan every drilling and excavation location; scanned area marked up.',
      'Safe digging practice to HSG47: hand-dig trial holes to prove services before mechanical excavation.',
      'Drill depth limited by a stop collar where the wall build-up is known; no blind drilling through a party or structural wall.',
      'Assume unmarked services are live until proven otherwise.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'elec-overhead-lines',
    category: 'electrical',
    hazard: 'Contact with overhead power lines by scaffold, ladders, MEWPs or a crane jib',
    technologies: ['solar_pv', 'small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Overhead lines identified at survey, their route marked on the site plan and the voltage confirmed with the DNO.',
      'Exclusion zones to HSE GS6 applied — minimum 9 m from lines on steel towers and 6 m from wooden poles unless a lesser distance is agreed in writing with the DNO.',
      'Goal posts and bunting erected at any crossing point; barriers set to prevent plant approaching the zone.',
      'Where the zone cannot be maintained, the line is diverted or made dead by the DNO before work begins.',
      'No handling of long conductive items (ladders, scaffold tube, mast sections) beneath or near a line.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },
  {
    id: 'elec-grid-backfeed',
    category: 'electrical',
    hazard: 'Unexpected re-energisation or back-feed from an inverter, generator or battery',
    technologies: ['solar_pv', 'battery_storage', 'small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'All embedded generation sources identified before isolation — PV, battery, wind, standby generator and UPS.',
      'Every source isolated and locked off individually; a single supply isolation is not sufficient.',
      'Proved dead at the point of work after all isolations, not before.',
      'Anti-islanding protection (G98/G99 compliant) verified at commissioning and recorded.',
      'Dual-supply warning labels fitted at the consumer unit, meter position and generation isolator to BS 7671 Section 712.',
      'DNO notified under G98, or a G99 application approved, before the system is energised.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'elec-temporary-supply',
    category: 'electrical',
    hazard: 'Use of damaged or unsuitable temporary power, leads and portable tools on site',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      '110 V CTE equipment used for site power wherever practicable; 230 V tools only where 110 V is not available and then via a 30 mA RCD.',
      'All portable equipment PAT tested and in date; label checked at the pre-start.',
      'Pre-use visual inspection of every lead, plug and casing; damaged equipment quarantined and labelled "DO NOT USE".',
      'Leads fully uncoiled from drums before use to prevent overheating.',
      'No use of the client supply without permission and an RCD at the point of connection.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'elec-earthing',
    category: 'electrical',
    hazard: 'Inadequate earthing or bonding leaving exposed metalwork at a dangerous potential',
    technologies: ['solar_pv', 'battery_storage', 'ashp', 'small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, CLIENT],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Existing earthing arrangement (TN-S, TN-C-S or TT) confirmed and recorded before design sign-off.',
      'Main protective bonding verified to BS 7671 and upgraded where undersized before energisation.',
      'Mounting frames and array metalwork bonded where required by the design; equipotential bonding conductors sized to Section 712.',
      'PME earthing restrictions observed for outdoor plant, EV and heat-pump installations; a separate earth electrode installed where required.',
      'Earth continuity, insulation resistance, polarity, earth fault loop impedance and RCD operation tested and recorded on the certificate before handover.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },

  // ==========================================================================
  // Manual handling
  // ==========================================================================
  {
    id: 'mh-panels',
    category: 'manual_handling',
    hazard: 'Musculoskeletal injury handling PV modules, which are large, heavy and act as a sail',
    technologies: ['solar_pv'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 3,
    controls: [
      'Two-person lift for every module as standard; suction handling aids or a panel lifter used on commercial arrays.',
      'Mechanical handling (hoist, telehandler, conveyor or panel lift) used to raise modules to roof level — never carried up a ladder.',
      'Modules never handled in wind above 23 mph: the panel behaves as a sail and control is lost.',
      'Route planned and cleared before the lift; loads not carried on scaffold boards without a clear, unobstructed path.',
      'Operatives trained in manual handling; loads kept close to the body, no twisting, no lifting above shoulder height.',
      'Deliveries broken down at ground level and staged close to the point of use.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'mh-battery-weight',
    category: 'manual_handling',
    hazard: 'Handling battery modules and inverters of significant concentrated weight in confined plant spaces',
    technologies: ['battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 3,
    controls: [
      'Unit weights confirmed from the datasheet at design stage and the handling method planned before delivery.',
      'Sack truck, stair climber or genie lift used for any unit over 25 kg; two-person lift as the minimum for all modules.',
      'Battery cabinets assembled in situ where the design allows, so individual modules are carried rather than the complete unit.',
      'Wall-mounted units offered up on a proprietary lifting bracket or temporary support ledger, never held by hand while fixing.',
      'Fixings and wall construction verified as adequate for the loaded weight before the unit is offered up.',
      'Floor loading confirmed with the client or a structural engineer where a cabinet is sited on a suspended floor.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'mh-ashp-unit',
    category: 'manual_handling',
    hazard: 'Handling heat pump units, cylinders and buffer vessels through restricted domestic access',
    technologies: ['ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 3,
    controls: [
      'Access route surveyed and measured before delivery; door and stair widths recorded and a handling plan agreed.',
      'Minimum two-person lift for outdoor units; four operatives or mechanical aid for units above 100 kg.',
      'Sack truck, stair-climbing trolley or crane offload used as appropriate; the unit is never manhandled up stairs.',
      'Cylinders moved empty and filled in position; never moved once filled.',
      'Lifting straps and the manufacturer lifting points used; the unit is not lifted by pipework or the casing.',
      'Route protected with floor coverings and corner guards to prevent trip and damage.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'mh-repetitive',
    category: 'manual_handling',
    hazard: 'Repetitive overhead working and awkward postures during luminaire replacement',
    technologies: ['led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 2,
    controls: [
      'Platform height adjusted so the work is at chest-to-shoulder height rather than fully overhead.',
      'Task rotation between operatives and a break from overhead work at least every hour.',
      'Luminaires pre-assembled at ground level so overhead time is limited to fixing and connection.',
      'Second operative supports the fitting during connection so no one holds a load overhead single-handed.',
      'Podium steps or a scissor lift used in preference to a stepladder to allow a stable, adjustable working height.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
    core: true,
  },

  // ==========================================================================
  // Lifting operations
  // ==========================================================================
  {
    id: 'lift-crane',
    category: 'lifting',
    hazard: 'Failure of a lifting operation — dropped load, crane overturn or contact with the load',
    technologies: ['solar_pv', 'small_wind', 'battery_storage', 'ashp'],
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES, PUBLIC, OTHER_TRADES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'A written lift plan is produced by an Appointed Person (CPCS A61 or equivalent) and briefed to everyone involved before the lift.',
      'Ground bearing pressure assessed and outrigger mats sized accordingly; the set-up position is proven before the first lift.',
      'All lifting accessories (slings, shackles, chains, spreader beams) are within their LOLER thorough examination date and are inspected before use; certificates held on site.',
      'Safe working load never exceeded; the load weight is confirmed, not estimated.',
      'Exclusion zone maintained beneath the load and the slew radius, barriered and policed by a slinger/signaller.',
      'Loads are never carried over occupied areas, public highway or other trades.',
      'Lift abandoned if wind exceeds the crane chart limit, or in poor visibility.',
      'Tag lines used to control the load; no hands on a suspended load.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'lift-turbine-erection',
    category: 'lifting',
    hazard: 'Turbine tower or mast erection — instability, uncontrolled movement and structural collapse',
    technologies: ['small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Erection to the manufacturer method statement and a lift plan by an Appointed Person; no improvisation on site.',
      'Foundation concrete cure strength confirmed against the design before any load is applied to the base.',
      'Gin pole, winch and guy anchors proof-loaded and inspected; anchors sized to the design pull.',
      'Exclusion zone of at least the full tower height plus 10% maintained on all sides throughout raising and lowering.',
      'Erection suspended if wind exceeds 8 m/s at ground level, or in rain, lightning or poor visibility.',
      'Rotor locked and blades secured before raising; blades fitted after the tower is up where the design allows.',
      'Only the erection crew inside the zone; a dedicated banksman controls all movements by radio.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'lift-stored-rotor',
    category: 'lifting',
    hazard: 'Stored energy in a wind turbine rotor — unexpected rotation during maintenance or install',
    technologies: ['small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Rotor mechanically locked with the manufacturer pin or brake and the lock physically verified before anyone approaches the hub.',
      'Turbine electrically isolated, short-circuited across the phases where the manufacturer specifies, and proved dead.',
      'Blades tied off to the tower to prevent windmilling in gusts.',
      'Lock-off tags applied at the isolator and the rotor lock; keys held by the operative at the hub.',
      'Work stopped and the rotor re-secured if wind rises during the task.',
      'No hands or body parts inside the rotor plane at any time.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },

  // ==========================================================================
  // Fire & thermal
  // ==========================================================================
  {
    id: 'fire-lithium',
    category: 'fire',
    hazard: 'Lithium-ion cell damage leading to thermal runaway, toxic off-gassing, fire or explosion',
    technologies: ['battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, PUBLIC],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Batteries inspected on delivery for impact damage, swelling, heat or electrolyte smell; any suspect unit is quarantined outdoors, away from the building, and returned unopened.',
      'Never drop, crush, puncture or drill near a battery module; enclosures are not opened beyond the manufacturer service points.',
      'Installed location complies with BS 7671, the manufacturer instruction and PAS 63100 — not in an escape route, loft, or against a habitable-room wall unless a fire-rated barrier is fitted.',
      'Minimum clearances and ventilation maintained exactly as specified; ambient temperature kept within the stated operating range.',
      'CO2 or dry-powder extinguisher and a fire blanket present during commissioning; operatives briefed that water is used only in volume, from a distance, and only by the fire service.',
      'A damaged or venting battery is treated as a fire: evacuate, do not attempt to isolate at close quarters, call 999 and state "lithium battery fire".',
      'Batteries transported to ADR / UN3480 requirements in the original packaging, secured and separated from the passenger compartment.',
      'System commissioned to the manufacturer procedure with BMS communications and cell balance verified before leaving site.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'fire-hot-works',
    category: 'fire',
    hazard: 'Fire from hot works — soldering, brazing, grinding or cutting near combustible material',
    technologies: ['ashp', 'solar_pv', 'led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'Hot works avoided by design wherever possible — press-fit or compression joints used in place of brazing.',
      'Where hot works are unavoidable, a hot works permit is raised, signed by the responsible person and closed out at the end.',
      'Combustible material removed within 6 m, or protected with a fire-resistant blanket; voids and cavities checked and sealed.',
      'Fire extinguisher (water and CO2) and a fire blanket to hand throughout, and a charged water sprayer for the fire watch.',
      'One-hour fire watch maintained after the last hot work, including a check of the far side of any wall or floor worked through.',
      'Hot works finish at least one hour before site closure; gas bottles turned off at the cylinder and removed from the building.',
      'Client fire alarm isolation agreed in writing where dust or fume could cause a false activation, and reinstated before leaving.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
  {
    id: 'fire-hot-surfaces',
    category: 'fire',
    hazard: 'Burns from hot pipework, flow temperatures, brazing equipment and hot luminaires',
    technologies: ['ashp', 'led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 2,
    controls: [
      'Heating system drained down and allowed to cool before any pipework is broken into.',
      'Existing luminaires switched off and allowed to cool for at least 10 minutes before removal — discharge fittings run very hot.',
      'Heat-resistant gloves worn for brazing and for handling recently worked pipe.',
      'Brazing torch secured in a stand when not in hand; the hot end is never laid on a surface.',
      'Hot surfaces flagged to others in the area with a warning sign until cool.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
  },
  {
    id: 'fire-arc-flash',
    category: 'fire',
    hazard: 'Arc flash at a distribution board or switchgear during connection to the incoming supply',
    technologies: 'all',
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Prospective short-circuit current established before work; the board is confirmed as adequately rated.',
      'Isolation upstream of the working position wherever practicable, with the supply company or client authorised person as required.',
      'Arc-rated coveralls, face shield and Class 0 gloves worn for any work at an energised board.',
      'Insulated tools to IEC 60900; no metal tape measures, jewellery or conductive lanyards.',
      'Board covers refitted before energisation; no unattended open panels at any time.',
      'A second competent person is present and briefed on emergency isolation and CPR.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },

  // ==========================================================================
  // Weather & environment
  // ==========================================================================
  {
    id: 'wx-wind',
    category: 'weather',
    hazard: 'High wind causing loss of control of panels, sheet materials, access equipment and operatives',
    technologies: ['solar_pv', 'small_wind', 'ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC],
    initialLikelihood: 4,
    initialSeverity: 4,
    controls: [
      'Met Office forecast checked the evening before and again at the pre-start briefing; recorded in the site diary.',
      'Roof work and panel handling stop at 23 mph (Beaufort 5); all work at height stops at 38 mph (Beaufort 8).',
      'Wind speed measured on site with an anemometer at the working position when conditions are marginal — not judged by feel.',
      'Turbine erection limits are tighter and are set by the manufacturer, typically 8 m/s at ground level.',
      'Materials, sheeting and debris netting secured or removed at the end of each shift and before any forecast high wind.',
      'Scaffold sheeting removed or ties increased ahead of a named storm.',
    ],
    residualLikelihood: 2,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'wx-rain-ice',
    category: 'weather',
    hazard: 'Wet, icy or frosted surfaces making roofs, ladders and platforms slippery',
    technologies: ['solar_pv', 'small_wind', 'ashp', 'led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 4,
    initialSeverity: 4,
    controls: [
      'No roof access on frost, ice, snow or standing water — glass modules and metal roofs become extremely slippery.',
      'Surfaces checked physically at the start of the shift, not assumed to have thawed.',
      'Work rescheduled rather than rushed; the client is informed early so pressure is not applied to continue.',
      'Where a scaffold is in place, boards are swept and gritted before use.',
      'Electrical terminations, DC connections and enclosure openings are not made in rain.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'wx-heat-cold',
    category: 'weather',
    hazard: 'Heat stress, sunburn, dehydration or cold injury during prolonged outdoor work',
    technologies: ['solar_pv', 'small_wind', 'ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Drinking water available on site at all times and taken regularly; operatives briefed on the signs of heat exhaustion.',
      'Work rotated and rest breaks taken in shade during hot weather; heavy tasks scheduled for the cooler part of the day.',
      'Sun cream (SPF 30 minimum) provided; long sleeves and a hard hat with a brim or neck cover worn.',
      'In cold weather, thermal layers and gloves provided, and a warm place for breaks agreed with the client.',
      'Roof temperatures can far exceed air temperature — direct contact with dark surfaces and modules is minimised.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
  },
  {
    id: 'wx-lightning',
    category: 'weather',
    hazard: 'Lightning strike while working at height, on a mast or handling long conductive items',
    technologies: ['solar_pv', 'small_wind'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Forecast checked for thunderstorm risk before mobilising; work not started when storms are forecast within the shift.',
      'All work at height and on masts stops at the first thunder heard, and does not resume until 30 minutes after the last thunder.',
      'Operatives descend and shelter in a vehicle or building — not under a tree, scaffold or the turbine itself.',
      'Handling of scaffold tube, mast sections and long conductive items ceases immediately.',
      'Array and turbine surge protection installed to the design and left in a safe state if work stops mid-task.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
  },
  {
    id: 'wx-environmental-harm',
    category: 'weather',
    hazard: 'Environmental harm from spillage, waste or disturbance to protected species and habitat',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: ['Environment', PUBLIC],
    initialLikelihood: 2,
    initialSeverity: 3,
    controls: [
      'Spill kit carried on every vehicle and available at the plant location; spills contained immediately and reported.',
      'Glycol, refrigerant, oils and cleaning chemicals stored on a bund or drip tray, away from drains and watercourses.',
      'Waste segregated and removed by a licensed carrier; duty-of-care transfer notes retained. WEEE, batteries and lamps go to a licensed route.',
      'Nesting birds and bats checked for before roof, loft and mast works; work stops and advice is sought if evidence is found (nesting birds are protected year-round).',
      'Noise-generating work restricted to agreed hours; dust suppressed at source.',
      'No burning of waste on site under any circumstances.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
    core: true,
  },

  // ==========================================================================
  // Public & occupants
  // ==========================================================================
  {
    id: 'pub-occupied-premises',
    category: 'public',
    hazard: 'Injury to occupants, customers or vulnerable persons in a building that stays in use',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OCCUPANTS, PUBLIC, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Work area physically segregated with barriers, screens or Heras fencing and clearly signed before work starts.',
      'Occupants briefed at the start of each day on which areas are affected and for how long.',
      'Work in occupied commercial areas planned for out-of-hours or phased so the public are never adjacent to live works.',
      'Particular care where vulnerable people are present — schools, care settings and healthcare — including DBS checks where the client requires them.',
      'Tools and materials never left unattended in an accessible area; the work area is left safe and clear at every break.',
      'Householders and pets kept clear of loft, roof and plant areas; access hatches closed when unattended.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'pub-highway',
    category: 'public',
    hazard: 'Work adjacent to a public footpath or highway — pedestrians entering the work area or falling zone',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [PUBLIC, OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Scaffolds and platforms over a footpath fitted with a fan, tunnel or full sheeting; a licence obtained from the highway authority where required.',
      'Pedestrian route maintained or a signed diversion agreed with the local authority — never simply blocked.',
      'Barriers with tapping rails and, where used at night, lit; barriers checked at the start and end of each shift.',
      'Deliveries scheduled outside school and rush-hour peaks where the site adjoins a busy route.',
      'Site vehicles never park across a footpath or a dropped kerb.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
  },
  {
    id: 'pub-power-interruption',
    category: 'public',
    hazard: 'Planned or unplanned interruption of supply affecting occupants, business or critical equipment',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OCCUPANTS, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Shutdown time and duration agreed with the client in writing at least 48 hours in advance.',
      'Critical loads identified before isolation — lifts, alarms, refrigeration, medical, IT and server equipment, care equipment.',
      'Vulnerable occupants and anyone dependent on powered medical equipment identified in advance and alternative arrangements confirmed.',
      'Boards labelled and circuits proven before isolation so only the intended circuit is affected.',
      'Supply restored and confirmed working before leaving site; the client signs to confirm reinstatement.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
  },

  // ==========================================================================
  // Hazardous substances
  // ==========================================================================
  {
    id: 'sub-asbestos',
    category: 'substances',
    hazard: 'Disturbance of asbestos-containing materials in pre-2000 buildings',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, CLIENT],
    initialLikelihood: 3,
    initialSeverity: 5,
    controls: [
      'The asbestos register or a refurbishment and demolition survey is obtained from the client and reviewed BEFORE any intrusive work; no register means no intrusive work.',
      'All operatives hold current asbestos awareness training (UKATA or equivalent), refreshed annually.',
      'Presumed ACMs — textured coatings, cement sheet roofing and cladding, insulating board ceiling tiles, pipe lagging, floor tiles, fuse-board flash guards — are not drilled, cut or broken.',
      'If suspect material is found or damaged, work stops immediately, the area is vacated and sealed, and the client and management are informed. Work does not resume until a licensed analysis clears it.',
      'Fuse-board flash guards and older lighting fittings are treated as suspect until proven otherwise.',
      'No sanding, drilling or dry sweeping in any area where ACMs are recorded.',
    ],
    residualLikelihood: 1,
    residualSeverity: 5,
    core: true,
  },
  {
    id: 'sub-refrigerant',
    category: 'substances',
    hazard: 'Refrigerant release — cold burns, asphyxiation in enclosed spaces and, for A2L gases, flammability',
    technologies: ['ashp'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS],
    initialLikelihood: 2,
    initialSeverity: 4,
    controls: [
      'All refrigerant work carried out only by F-Gas certified engineers (Category I under EU 2015/2067); certificate held on file and attached to this document.',
      'R32 and other A2L refrigerants are mildly flammable: no ignition sources, no smoking and no hot works within the charge area; minimum room-area requirements checked against the charge size before siting.',
      'Recovery equipment used for any decommissioning — venting to atmosphere is a criminal offence.',
      'Gauntlets and eye protection worn when breaking into the refrigerant circuit; liquid refrigerant causes immediate cold burns.',
      'Pressure test with oxygen-free nitrogen and evacuate to the manufacturer specification; never pressure test with oxygen or compressed air.',
      'Leak test on completion and the charge, system and test results logged in the F-Gas record.',
      'Adequate ventilation maintained when working in a plant room or other enclosed space.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'sub-coshh-general',
    category: 'substances',
    hazard: 'Exposure to sealants, solvents, flux, glycol and cleaning products used in the installation',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 2,
    controls: [
      'A COSHH assessment and the safety data sheet are held for every substance brought to site; both are in the site pack.',
      'Products used in a well-ventilated area, following the manufacturer instruction; substituted for a lower-hazard product where one exists.',
      'Nitrile gloves and eye protection worn when decanting or applying; RPE where the SDS requires it and face-fit tested.',
      'Containers kept closed, labelled and stored upright in the van in a designated box, away from heat and ignition sources.',
      'Eyewash and skin cleanser available; contaminated clothing changed rather than worn on.',
      'Glycol treated as a harmful substance — no siphoning by mouth, and spills contained and removed.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'sub-dust-silica',
    category: 'substances',
    hazard: 'Respirable crystalline silica and general construction dust from drilling, chasing and coring',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS],
    initialLikelihood: 4,
    initialSeverity: 4,
    controls: [
      'On-tool extraction (M-class vacuum) or water suppression used for all drilling, chasing and coring — dry cutting without control is not permitted.',
      'FFP3 disposable or reusable half-mask RPE worn, face-fit tested to the individual and clean-shaven at the seal.',
      'Work area segregated and dust screens used in occupied premises; extraction to the outside where practicable.',
      'Housekeeping by M-class vacuum only — never dry sweeping or blowing down with compressed air.',
      'Health surveillance in place for operatives regularly exposed to silica dust.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
  },
  {
    id: 'sub-lamp-disposal',
    category: 'substances',
    hazard: 'Breakage of fluorescent or discharge lamps releasing mercury vapour and glass',
    technologies: ['led_lighting'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Lamps removed one at a time, kept horizontal and placed straight into a purpose-made lamp coffin or tube box.',
      'Gloves and eye protection worn; lamps never stacked loose in a van or bin bag.',
      'If a lamp breaks, the area is ventilated and vacated for 15 minutes, fragments collected with stiff card and damp paper (never a domestic vacuum) and double-bagged.',
      'All lamps, luminaires and control gear removed as WEEE and taken to a licensed treatment facility; transfer notes retained.',
      'Older capacitors and ballasts may contain PCBs — these are segregated and disposed of as hazardous waste.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'sub-legionella',
    category: 'substances',
    hazard: 'Legionella risk from stored hot water systems commissioned at low temperature',
    technologies: ['ashp'],
    sectors: 'all',
    whoIsAtRisk: [OCCUPANTS, OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 4,
    controls: [
      'Cylinder sized and controls set so a weekly pasteurisation cycle reaches at least 60 degrees C at the store, per HSG274 Part 2.',
      'Distribution temperature maintained at 50 degrees C or above; thermostatic mixing valves fitted at outlets to prevent scalding.',
      'System flushed and chlorinated before handover where required; dead legs designed out.',
      'Client briefed at handover on the pasteurisation cycle, the risk of disabling it, and on flushing outlets after any period of non-use.',
      'Commissioning temperatures recorded on the handover certificate.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
  },

  // ==========================================================================
  // Plant & equipment
  // ==========================================================================
  {
    id: 'plant-power-tools',
    category: 'plant',
    hazard: 'Injury from power tools — cuts, entanglement, ejected material and kickback',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Only trained operatives use power tools; all guards fitted, in place and functional before use.',
      'Pre-use inspection of the tool, blade, disc and lead; damaged equipment quarantined.',
      'Correct disc for the material, within its expiry date, and run up to speed away from the body.',
      'Eye protection to EN 166 worn for all cutting, drilling and grinding; gloves not worn near rotating spindles.',
      'Loose clothing, long hair and lanyards secured; jewellery removed.',
      'Tools isolated and unplugged before changing an accessory.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
    core: true,
  },
  {
    id: 'plant-noise',
    category: 'plant',
    hazard: 'Noise-induced hearing loss from core drilling, cutting, fixing and plant',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Quieter tools and methods selected at planning stage; noise reduced at source before relying on PPE.',
      'Hearing protection (SNR appropriate to the tool) worn whenever the daily exposure could exceed 80 dB(A) — as a rule, whenever you must raise your voice at 2 m.',
      'Noisy tasks kept short and rotated between operatives; exposure time limited.',
      'Occupants and neighbours warned before noisy work; hours restricted by agreement.',
      'Health surveillance for operatives regularly above the upper exposure action value.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
  },
  {
    id: 'plant-vibration',
    category: 'plant',
    hazard: 'Hand-arm vibration syndrome from prolonged use of hammer drills and breakers',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Trigger times monitored against the manufacturer vibration magnitude; the daily exposure action value of 2.5 m/s2 A(8) is not exceeded without management authorisation.',
      'Low-vibration tools with anti-vibration handles selected; sharp bits and correct consumables used so the tool does the work.',
      'Task rotation and regular breaks; no single operative carries out all the drilling on an array.',
      'Hands kept warm and dry; gloves provided in cold weather to maintain circulation.',
      'Health surveillance in place; operatives report tingling or numbness in fingers immediately.',
    ],
    residualLikelihood: 2,
    residualSeverity: 2,
  },
  {
    id: 'plant-telehandler',
    category: 'plant',
    hazard: 'Collision, overturn or crushing involving a telehandler, forklift or site vehicle',
    technologies: ['solar_pv', 'small_wind', 'battery_storage'],
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES, OTHER_TRADES, PUBLIC],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Operators hold a current CPCS/NPORS card for the machine; daily pre-use checks recorded.',
      'Pedestrian and vehicle routes segregated with barriers; a banksman controls all reversing and blind manoeuvres.',
      'Load charts observed; loads never lifted above people and never carried with the boom extended in travel.',
      'Machine parked with forks or attachment grounded, brake applied, isolated and keys removed when unattended.',
      'Site speed limit observed; high-visibility clothing worn by everyone in the operating area.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },

  // ==========================================================================
  // Structural
  // ==========================================================================
  {
    id: 'str-roof-loading',
    category: 'structural',
    hazard: 'Roof structure inadequate for the additional dead and wind load of an array',
    technologies: ['solar_pv'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, OCCUPANTS, PUBLIC],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Structural appraisal completed before installation — by a chartered structural engineer for any commercial roof, ballasted system or roof of uncertain condition.',
      'Rafter dimensions, spacing, span and condition recorded at survey and checked against the MCS 012 / MIS 3002 assessment.',
      'Ballast weights and layout follow the wind-load calculation for the site exposure category; ballast is never increased on site without a re-check.',
      'Roof covering, battens, fixings and any rot or beetle damage inspected; defects reported and remedied before mounting.',
      'Fixings into rafters, not battens or sarking alone; correct pilot hole and torque used.',
      'Work stops and management is informed if the structure differs materially from the survey.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
    core: true,
  },
  {
    id: 'str-penetration',
    category: 'structural',
    hazard: 'Water ingress or structural damage from roof and wall penetrations',
    technologies: ['solar_pv', 'ashp', 'small_wind'],
    sectors: 'all',
    whoIsAtRisk: [CLIENT, OCCUPANTS],
    initialLikelihood: 3,
    initialSeverity: 3,
    controls: [
      'Penetrations weatherproofed to the manufacturer detail as they are made, never left open overnight.',
      'Temporary weatherproofing in place before leaving site at any stage, and checked if rain is forecast.',
      'Flashings, cloaks and seals of the correct type for the roof covering; no reliance on sealant alone.',
      'Existing membrane on flat roofs protected with slip sheets; any repair carried out by the membrane manufacturer approved installer to preserve the warranty.',
      'Photographic record of every penetration taken before it is covered.',
    ],
    residualLikelihood: 1,
    residualSeverity: 2,
  },
  {
    id: 'str-foundation',
    category: 'structural',
    hazard: 'Excavation collapse or foundation failure during turbine base or ground-mount installation',
    technologies: ['small_wind', 'solar_pv'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Excavation design and support to CDM 2015 and HSG185; no entry into an unsupported excavation over 1.2 m.',
      'Battering, benching or proprietary trench support installed as the ground conditions require; inspected daily and after rain.',
      'Spoil and plant kept at least 1 m back from the edge; edge protection or barriers around any open excavation.',
      'Ladder access provided within 8 m of any working position in an excavation.',
      'Foundation design by a qualified engineer with ground conditions confirmed by a site investigation; concrete cure strength verified before loading.',
      'Excavations covered or fenced and lit outside working hours.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },

  // ==========================================================================
  // Confined & restricted spaces
  // ==========================================================================
  {
    id: 'conf-loft',
    category: 'confined',
    hazard: 'Restricted, hot, poorly lit loft and ceiling-void working with fall-through and insulation exposure',
    technologies: ['solar_pv', 'ashp', 'led_lighting', 'battery_storage'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Crawl boards laid across joists before entry; no standing or kneeling on plasterboard between joists at any time.',
      'Adequate task lighting installed before entry — never rely on a phone torch or a single inspection lamp.',
      'Head protection (bump cap) and knee pads worn; nails, roofing screws and sharp edges anticipated.',
      'Disposable coveralls, gloves and FFP3 RPE worn where mineral wool insulation is disturbed.',
      'Loft hatch kept clear and a second person aware of the entry; never lone working in a roof void without check-in arrangements.',
      'Loft temperature checked in summer; work rotated and hydration maintained.',
      'Any suspect ACM insulating board or lagging triggers an immediate stop.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'conf-plant-room',
    category: 'confined',
    hazard: 'Work in a plant room, riser or basement with limited ventilation and restricted escape',
    technologies: ['ashp', 'battery_storage'],
    sectors: ['commercial'],
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Space assessed against the Confined Spaces Regulations 1997 before entry; where it is a confined space, a permit and a trained entry team are required.',
      'Refrigerant leak detection and forced ventilation confirmed operational before entry where refrigerant plant is present.',
      'Atmosphere tested where there is any doubt; entry refused on an unsatisfactory reading.',
      'Continuous communication with a person outside the space; the door is never allowed to lock behind the entrant.',
      'Emergency lighting and a clear escape route confirmed; the route is not used for material storage.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },

  // ==========================================================================
  // Lone & remote working
  // ==========================================================================
  {
    id: 'lone-working',
    category: 'lone_working',
    hazard: 'Lone or remote working with delayed discovery of an accident or medical emergency',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Lone working is not permitted for work at height, live electrical work, hot works, confined spaces or any lifting operation.',
      'Where lone working is acceptable, a check-in schedule is agreed with the office and an escalation time set; a missed check-in triggers a call and then attendance.',
      'Mobile signal confirmed at the site; a satellite messenger or a second means of communication is carried on remote sites.',
      'Location, expected finish time and vehicle registration recorded with the office before travel.',
      'Personal safety considered for domestic visits: withdraw and report if a situation feels unsafe or a customer is hostile.',
      'First-aid kit and a charged phone carried at all times.',
    ],
    residualLikelihood: 1,
    residualSeverity: 3,
    core: true,
  },
  {
    id: 'lone-remote-site',
    category: 'lone_working',
    hazard: 'Remote rural site with long emergency-services response and poor access',
    technologies: ['small_wind', 'solar_pv'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Grid reference or what3words location for the site entrance and the working position recorded on the cover sheet of this document.',
      'Nearest A&E identified with the route and drive time; the local ambulance station informed on high-risk lifts where practicable.',
      'Minimum of two operatives on site at all times; at least one holds a current first-aid at work certificate.',
      'Enhanced first-aid provision carried, including a trauma dressing and a foil blanket.',
      'Access route confirmed passable for an ambulance and kept clear of parked vehicles.',
      'Livestock, farm machinery and unfenced water hazards identified with the landowner at the pre-start.',
    ],
    residualLikelihood: 2,
    residualSeverity: 3,
  },

  // ==========================================================================
  // Occupational health
  // ==========================================================================
  {
    id: 'health-uv-glare',
    category: 'health',
    hazard: 'UV exposure and glare from reflective roof surfaces and module glass',
    technologies: ['solar_pv'],
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES],
    initialLikelihood: 3,
    initialSeverity: 2,
    controls: [
      'Wraparound safety glasses with a UV filter worn on bright days.',
      'Skin covered with long sleeves; SPF 30+ applied to exposed skin and reapplied through the day.',
      'Operatives briefed to report any changing mole or persistent skin lesion.',
    ],
    residualLikelihood: 2,
    residualSeverity: 1,
  },
  {
    id: 'health-fatigue',
    category: 'health',
    hazard: 'Fatigue from long shifts, early starts and driving between sites',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC],
    initialLikelihood: 3,
    initialSeverity: 4,
    controls: [
      'Working hours planned so no operative exceeds 12 hours including travel; consecutive long days avoided.',
      'Overnight accommodation booked where the drive home after a full shift would be excessive.',
      'Breaks taken away from the work face; driving breaks of 15 minutes every 2 hours.',
      'Operatives have a duty to declare if they are not fit to work — including fatigue, illness, medication or the after-effects of alcohol — and will not be penalised for doing so.',
      'Safety-critical tasks are not scheduled for the end of a long shift.',
    ],
    residualLikelihood: 2,
    residualSeverity: 3,
  },
  {
    id: 'health-drugs-alcohol',
    category: 'health',
    hazard: 'Impairment through alcohol, drugs or prescription medication affecting safety-critical work',
    technologies: 'all',
    sectors: 'all',
    whoIsAtRisk: [OPERATIVES, PUBLIC, OTHER_TRADES],
    initialLikelihood: 2,
    initialSeverity: 5,
    controls: [
      'Company drug and alcohol policy applies on every site; being under the influence at work is a disciplinary matter.',
      'Operatives must declare prescription medication that carries a drowsiness or impairment warning before undertaking work at height, electrical work or driving.',
      'Supervisors challenge and stand down anyone who appears unfit; the decision is recorded.',
      'Client site testing regimes are complied with in full.',
    ],
    residualLikelihood: 1,
    residualSeverity: 4,
  },
];

/** Hazards offered for a given technology + sector. */
export function hazardsFor(technology: TechnologyId, sector: Sector): HazardTemplate[] {
  return HAZARD_LIBRARY.filter(
    (h) =>
      (h.technologies === 'all' || h.technologies.includes(technology)) &&
      (h.sectors === 'all' || h.sectors.includes(sector))
  );
}

/** Hazards pre-selected when a new document is created. */
export function coreHazardsFor(technology: TechnologyId, sector: Sector): HazardTemplate[] {
  return hazardsFor(technology, sector).filter((h) => h.core);
}

export function hazardById(id: string): HazardTemplate | undefined {
  return HAZARD_LIBRARY.find((h) => h.id === id);
}

export function categoryLabel(id: HazardCategory): string {
  return HAZARD_CATEGORIES.find((c) => c.id === id)?.label ?? id;
}
